### ISSUE TITLE
Error when downloading a big playlist

### ISSUE THREAD

**Issue by palmenros** [cooperhammond/irs#41]
When trying to download a big playlist, it crashes after the line `Trying to bypass google captcha.`
This line occurs after downloading some tracks.

The error is the following:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/irs/ripper.py", line 229, in find_yt_url
    return ("https://youtube.com" + self.code["href"], self.code["title"])
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/chromedriver': '/usr/local/bin/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/irs", line 11, in <module>
    load_entry_point('irs==6.7.6', 'console_scripts', 'irs')()
  File "/usr/lib/python3.6/site-packages/irs/cli.py", line 82, in main
    console(ripper)
  File "/usr/lib/python3.6/site-packages/irs/utils.py", line 361, in console
    ripper.spotify_list("playlist", list_name, username)
  File "/usr/lib/python3.6/site-packages/irs/ripper.py", line 356, in spotify_list
    locations = self.list(tracks)
  File "/usr/lib/python3.6/site-packages/irs/ripper.py", line 369, in list
    loc = self.song(track["name"], track["artist"], track)
  File "/usr/lib/python3.6/site-packages/irs/ripper.py", line 429, in song
    video_url, video_title = self.find_yt_url(song, artist)
  File "/usr/lib/python3.6/site-packages/irs/ripper.py", line 226, in find_yt_url
    return self.find_yt_url(song, artist, additional_search, caught_by_google, first, tries=tries + 1)
  File "/usr/lib/python3.6/site-packages/irs/ripper.py", line 226, in find_yt_url
    return self.find_yt_url(song, artist, additional_search, caught_by_google, first, tries=tries + 1)
  File "/usr/lib/python3.6/site-packages/irs/ripper.py", line 226, in find_yt_url
    return self.find_yt_url(song, artist, additional_search, caught_by_google, first, tries=tries + 1)
  [Previous line repeated 1 more times]
  File "/usr/lib/python3.6/site-packages/irs/ripper.py", line 224, in find_yt_url
    return self.find_yt_url(song, artist, additional_search, caught_by_google, first=True, tries=tries + 1)
  File "/usr/lib/python3.6/site-packages/irs/ripper.py", line 234, in find_yt_url
    return self.find_yt_url(song=song, artist=artist, additional_search=additional_search, caught_by_google=True, tries=tries + 1)
  File "/usr/lib/python3.6/site-packages/irs/ripper.py", line 159, in find_yt_url
    soup = BeautifulSoup(CaptchaCheat.cheat_it(link), 'html.parser')
  File "/usr/lib/python3.6/site-packages/irs/utils.py", line 469, in cheat_it
    with Browser('chrome', **executable_path) as b:
  File "/usr/lib/python3.6/site-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/splinter/driver/webdriver/chrome.py", line 35, in __init__
    self.driver = Chrome(chrome_options=options, **kwargs)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```
Also, executing `whereis chromedriver` produces `/usr/bin/chromedriver`, and `/usr/bin` is in PATH.

Thank you

**Comment by palmenros** [comment]
It downloaded 17 tracks before crashing, so a temporary workaround would be to split the playlist into different playlists with at most 17 tracks.

**Comment by palmenros** [comment]
Update: It only crashes with that song. The song is `Rockabye` from `Clean Bandit`

**Comment by kepoorhampond** [comment]
So if you download the song by itself does it crash? Does downloading the entire playlist without that song work fine?

**Comment by palmenros** [comment]
Yes, if you download the song by itself, it crashes

**Comment by kepoorhampond** [comment]
Could you post the error for just the song by itself? I'm unable to reproduce the bug, sorry :disappointed: Does downloading the entire playlist without that song work fine?

**Comment by Vorkhan** [comment]
This is happening to me as well, I think it's because I don't have `chromium-browser` installed and so I can't bypass google's captcha.

I will try installing chromium and see if it changes anything.

**Comment by Vorkhan** [comment]
Ok the problem (at least for me) was that I had the chromedriver executable under /usr/bin utils.py couldn't find it.
