### ISSUE TITLE
Issue downloading

### ISSUE THREAD

**Issue by Mixie-12** [cooperhammond/irs#48]
So the script starts up fine. The spotify token works. I run Python 3.6.6

But when i try to download, i encounter this error:
Album name: currents
Album: "b'Currents'" by "b'Tame Impala'"
Finding Youtube link ...
Downloading "Let It Happen" by "Tame Impala"
Converting to mp3 ...
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 2047, in post_process
    files_to_delete, info = pp.run(info)
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 243, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Magnus\AppData\Local\Programs\Python\Python36\Scripts\irs.exe\__main__.py", line 9, in <module>
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\irs\cli.py", line 82, in main
    console(ripper)
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\irs\utils.py", line 354, in console
    ripper.spotify_list("album", album_name)
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\irs\ripper.py", line 356, in spotify_list
    locations = self.list(tracks)
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\irs\ripper.py", line 369, in list
    loc = self.song(track["name"], track["artist"], track)
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\irs\ripper.py", line 453, in song
    ydl.download([video_url])
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 2001, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 803, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 857, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 1635, in process_video_result
    self.process_info(new_info)
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 1982, in process_info
    self.post_process(filename, info_dict)
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 2049, in post_process
    self.report_error(e.msg)
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 620, in report_error
    self.trouble(error_message, tb)
  File "c:\users\magnus\appdata\local\programs\python\python36\lib\site-packages\youtube_dl\YoutubeDL.py", line 590, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: WARNING: unable to obtain file audio codec with ffprobe

I have ffprobe installed with pip, so dont see why there would be a error

**Comment by cooperhammond** [comment]
Try to run `irs --setup`. #55 hopefully fixes this.
