### ISSUE TITLE
Signature Extraction Failed

### ISSUE THREAD

**Issue by Mhowser** [cooperhammond/irs#49]
Ubuntu 16.04 python 2.7
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 797, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'/yts/jsbin/player_ias-vflH-Ze7P/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'/yts/jsbin/player_ias-vflH-Ze7P/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/irs", line 9, in <module>
    load_entry_point('irs==6.7.7', 'console_scripts', 'irs')()
  File "/usr/local/lib/python2.7/dist-packages/irs/cli.py", line 82, in main
    console(ripper)
  File "/usr/local/lib/python2.7/dist-packages/irs/utils.py", line 350, in console
    ripper.song(song_name, artist_name)
  File "/usr/local/lib/python2.7/dist-packages/irs/ripper.py", line 453, in song
    ydl.download([video_url])
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1692, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 681, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 541, in report_error
    self.trouble(error_message, tb)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 511, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 797, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'/yts/jsbin/player_ias-vflH-Ze7P/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'/yts/jsbin/player_ias-vflH-Ze7P/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Mhowser** [comment]
This is caused by using an outdated version of Youtube-dl. uninstalling and installing the latest version fixed this issue.
