### ISSUE TITLE
Keep getting errror related to chrome webdriver

### ISSUE THREAD

**Issue by amit-bhandari** [cooperhammond/irs#52]
I keep getting following error.

selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

I have downloaded chrome webdriver and installed it in system path as well.

I am using UBUNTU 16.04

**Comment by parseHex** [comment]
Had this error using Ubuntu 18.10 as well, also had chome webdriver in PATH.

**Comment by amit-bhandari** [comment]
Did you find solution? @parseHex

**Comment by parseHex** [comment]
Just took a try at getting it to work and succeeded. I don't know if it's what you're _supposed_ to do but here's what I did:

- Downloaded chromedriver from [here](https://sites.google.com/a/chromium.org/chromedriver/downloads). I'm on Chromium v71 so I got the download labelled "ChromeDriver 71.0.3578.137".
- Copied the unzipped `chromedriver` to `/usr/local/bin`, and I changed its permissions to match the other files there, so `sudo chmod 755 /usr/local/bin/chromedriver` (if you don't change the permissions then you'll get a new error).

**Comment by amit-bhandari** [comment]
I tried your steps but I don't know what's wrong with irs, it's opening chromium browser upon execution. Used to work flawlessly couple months back.

**Comment by parseHex** [comment]
It opens Chromium when you execute the `irs` command? Is there a message toward the top of the browser window saying something along the lines of "Chrome is being control by automated test software."? If so then that's normal I think - it looks like `irs` controls Chromium to bypass YouTube's captcha.

It took a minute or two to download a song but it finished eventually and I found the song in my home directory's Music folder.

**Comment by amit-bhandari** [comment]
Yes, it said the title which you mentioned. 

But still it crashed saying this on traceback.

`Traceback (most recent call last):
  File "/home/ab/.local/lib/python3.5/site-packages/irs/ripper.py", line 229, in find_yt_url
    return ("https://youtube.com" + self.code["href"], self.code["title"])
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ab/.local/bin/irs", line 11, in <module>
    sys.exit(main())
  File "/home/ab/.local/lib/python3.5/site-packages/irs/cli.py", line 82, in main
    console(ripper)
  File "/home/ab/.local/lib/python3.5/site-packages/irs/utils.py", line 350, in console
    ripper.song(song_name, artist_name)
  File "/home/ab/.local/lib/python3.5/site-packages/irs/ripper.py", line 429, in song
    video_url, video_title = self.find_yt_url(song, artist)
  File "/home/ab/.local/lib/python3.5/site-packages/irs/ripper.py", line 226, in find_yt_url
    return self.find_yt_url(song, artist, additional_search, caught_by_google, first, tries=tries + 1)
  File "/home/ab/.local/lib/python3.5/site-packages/irs/ripper.py", line 226, in find_yt_url
    return self.find_yt_url(song, artist, additional_search, caught_by_google, first, tries=tries + 1)
  File "/home/ab/.local/lib/python3.5/site-packages/irs/ripper.py", line 226, in find_yt_url
    return self.find_yt_url(song, artist, additional_search, caught_by_google, first, tries=tries + 1)
  File "/home/ab/.local/lib/python3.5/site-packages/irs/ripper.py", line 226, in find_yt_url
    return self.find_yt_url(song, artist, additional_search, caught_by_google, first, tries=tries + 1)
  File "/home/ab/.local/lib/python3.5/site-packages/irs/ripper.py", line 226, in find_yt_url
    return self.find_yt_url(song, artist, additional_search, caught_by_google, first, tries=tries + 1)
  File "/home/ab/.local/lib/python3.5/site-packages/irs/ripper.py", line 224, in find_yt_url
    return self.find_yt_url(song, artist, additional_search, caught_by_google, first=True, tries=tries + 1)
  File "/home/ab/.local/lib/python3.5/site-packages/irs/ripper.py", line 234, in find_yt_url
    return self.find_yt_url(song=song, artist=artist, additional_search=additional_search, caught_by_google=True, tries=tries + 1)
  File "/home/ab/.local/lib/python3.5/site-packages/irs/ripper.py", line 159, in find_yt_url
    soup = BeautifulSoup(CaptchaCheat.cheat_it(link), 'html.parser')
  File "/home/ab/.local/lib/python3.5/site-packages/irs/utils.py", line 472, in cheat_it
    while CaptchaCheat.strip_it(b.evaluate_script("document.URL")) != CaptchaCheat.strip_it(url):
  File "/home/ab/.local/lib/python3.5/site-packages/irs/utils.py", line 478, in strip_it
    s = s.strip("http://")
TypeError: a bytes-like object is required, not 'str'
`

**Comment by parseHex** [comment]
Okay so I dug around a little bit and was able to get this error on my machine. It looks like this error is related to Python 3. I had it installed with 2 before so I didn't get the error and got it when I switched.

Try uninstalling Python 3's version and install Python 2's and see if that helps.

**Comment by amit-bhandari** [comment]
Okay let me try with python 2

**Comment by cooperhammond** [comment]
So I removed the chromedriver entirely with #55, so there's no getting around the captcha _yet_. In the future I'll bring back the captcha cheater.
