### ISSUE TITLE
tput: unknown terminal "xterm-termite"

### ISSUE THREAD

**Issue by JPUnD** [cooperhammond/irs#54]
Hi there,

So i've just installed irs, from within a conda env, followed the instructions and got this error:

**tput: unknown terminal "xterm-termite"**

To install irs i did as follows:

- Created an empty conda env
- Installed Python 3.7 and pip in it by using "conda install python"
- Installed irs using pip without sudo (not required to use sudo in conda env)
- Ran irs --setup
- Got the following error when i ran the command "irs":

tput: unknown terminal "xterm-termite"
Traceback (most recent call last):
  File "/home/undercover/.conda/envs/irs/bin/irs", line 6, in <module>
    from irs.cli import main
  File "/home/undercover/.conda/envs/irs/lib/python3.7/site-packages/irs/__init__.py", line 20, in <module>
    from .ripper import Ripper
  File "/home/undercover/.conda/envs/irs/lib/python3.7/site-packages/irs/ripper.py", line 21, in <module>
    from .utils import YdlUtils, ObjManip, Config, CaptchaCheat
  File "/home/undercover/.conda/envs/irs/lib/python3.7/site-packages/irs/utils.py", line 461, in <module>
    from splinter import Browser
  File "/home/undercover/.conda/envs/irs/lib/python3.7/site-packages/splinter/__init__.py", line 5, in <module>
    from splinter.browser import Browser  # NOQA
  File "/home/undercover/.conda/envs/irs/lib/python3.7/site-packages/splinter/browser.py", line 9, in <module>
    from splinter.driver.webdriver.firefox import WebDriver as FirefoxWebDriver
  File "/home/undercover/.conda/envs/irs/lib/python3.7/site-packages/splinter/driver/webdriver/__init__.py", line 16, in <module>
    from six import BytesIO
ModuleNotFoundError: No module named 'six'

Sorry about the formatting, kinda suck at it, and after searching for the error, i found no fix related to irs, and i don't understand what's causing it either. Everything else in my machine works fine, and all the terminal base applications i use run correctly.

**Comment by JPUnD** [comment]
Just found out it happens the exact same thing with urxvt-unicode "tput: unknown terminal "rxvt-unicode-256color"", so i'm assuming it's not an irs problem but a problem i somehow created by miss configuring my system.

**Comment by cooperhammond** [comment]
So with the latest update (#55), I think this problem should be gone entirely. The CLI is gone but will be coming back in the future.
