### ISSUE TITLE
youtube-dl error when searching for URL

### ISSUE THREAD

**Issue by vndreiii** [cooperhammond/irs#86]
Youtube has changed the way it organizes its webpage and thus made the whole program unusable, please update youtube-dl binaries or perhaps fix the way it searches for URL, my suggestion would also be to use ytp-dl

**Comment by luk-brue** [comment]
Here is the error, reproducible with any song for me. How can I fix this?
 
Input: `$ ~/apps/irs/bin/irs --song "Bohemian Rhapsody" --artist "Queen"
`
Output:

```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/elbe/apps/irs/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1360, in _decrypt_signature
    func = self._extract_signature_function(
  File "/home/elbe/apps/irs/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1277, in _extract_signature_function
    cache_res = res(test_string)
  File "/home/elbe/apps/irs/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1344, in <lambda>
    return lambda s: initial_function([s])
  File "/home/elbe/apps/irs/bin/youtube-dl/youtube_dl/jsinterp.py", line 258, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "/home/elbe/apps/irs/bin/youtube-dl/youtube_dl/jsinterp.py", line 56, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "/home/elbe/apps/irs/bin/youtube-dl/youtube_dl/jsinterp.py", line 182, in interpret_expression
    return obj[member](argvals)
KeyError: 'QV'
 (caused by KeyError('QV')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```
